// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eubrgxjbfnqeqsyansrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1YnJneGpiZm5xZXFzeWFuc3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNTMzMzksImV4cCI6MjA3MjgyOTMzOX0.RzYAwnWl1nk6Ylnr4ZOqshXgKAEOb3HPS40Q4IQeh64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});